services:
  sshwifty:
    image: niruix/sshwifty:latest
    container_name: sshwifty
    restart: unless-stopped
    environment:
      - SSHWIFTY_SHAREDKEY=${SSHWIFTY_SHAREDKEY}
    extra_hosts:
      - "setiadyslabs:host-gateway"
    networks:
      - shared-network

networks:
  shared-network:
    external: true